export const ADD_FILTER = 'projectsMain/ADD_FILTER'
export const REMOVE_FILTER = 'projectsMain/REMOVE_FILTER'
export const CLEAR_FILTERS = 'projectsMain/CLEAR_FILTERS'
export const SAVE_PROJECTS = 'projectsMain/SAVE_PROJECTS'
export const TOGGLE_LIKE = 'projectsMain/TOGGLE_LIKE'
