export const SAVE_USER_PROJECTS = 'auth/user/SAVE_USER_PROJECTS'
export const SAVE_USER_COMMENTS = 'auth/user/SAVE_USER_COMMENTS'
export const SAVE_USER_BOOKMARKS = 'auth/user/SAVE_USER_BOOKMARKS'
export const SAVE_USER_LIKES = 'auth/user/SAVE_USER_LIKES'
export const SAVE_USER_LATEST_PROJECT = 'auth/user/SAVE_USER_LATEST_PROJECT'
