version: "3.6"

services:
  forum:
    image: appliedblockchain/node-bb-atrium
    build:
      context: packages/node-bb
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password123
      - ADMIN_EMAIL=test@unicef.com
      - URL=localhost
      - PORT=4567
      - SESSION_SECRET=raging-dog-cat
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=forum
    command: sh -ac 'echo "{\"url\":\"$$URL\",\"port\":\"$$PORT\",\"secret\":\"$$SESSION_SECRET\",\"database\":\"mongo\",\"mongo\":{\"host\":\"$$DATABASE_HOST\",\"port\":\"$$DATABASE_PORT\",\"database\":\"$$DATABASE_NAME\"}}" > config.json && node app --setup "{\"admin:username\":\"$$ADMIN_USERNAME\",\"admin:password\":\"$$ADMIN_PASSWORD\",\"admin:password:confirm\":\"$$ADMIN_PASSWORD\",\"admin:email\":\"$$ADMIN_EMAIL\"}" --defaultPlugins "[\"nodebb-plugin-session-sharing\", \"nodebb-plugin-mentions\"]" && ./nodebb start'
    ports:
      - 4567:4567

  remix:
    image: appliedblockchain/remix-atrium
    build:
      context: packages/remix
      dockerfile: Dockerfile
    depends_on:
      - parity1
    ports:
      - 8080:80

  app:
    image: asherbuck/atrium-web-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unin-app
    command: ./bin/entrypoint.sh
    working_dir: /node/app
    depends_on:
      - discovery
      - ganache
      - mongo
    volumes:
      - ./packages/app:/node/app
      - ./packages/blockchain:/node/blockchain
      - contracts:/contracts
    environment:
      - MONGO_URI=mongodb://mongo:27017/app
      - SECRET_OR_KEY=raging-dog-cat
      - PORT=5000
      - ETHEREUM_NODE=ganache
      - ETHEREUM_PROVIDER_URL=http://$ETHEREUM_NODE:8545
      - ATRIUM_WALLET_SECRET=dev
      - TRUFFLE_NETWORK=docker_development
    ports:
      - 5000:5000
      - 9229:9229
    restart: always

  discovery:
    hostname: discovery
    image: redis
    volumes:
      - discovery:/data


  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: --debug --gasLimit 9900000000 --gasPrice 0

  parity1:
    image: appliedblockchain/parity-solo
    environment:
      - PARITY_ID=1
    depends_on:
      - discovery
    ports:
      # - 8180:8180
      - 8545:8545
      - 8546:8546
      # - 8546:8546
      - 30303:30303
    volumes:
      - parity1_data:/parity/data
      - ./packages/blockchain:/parity/blockchain
    depends_on:
      - discovery

  ui:
    image: node:erbium-alpine3.11
    container_name: unin-client
    command: npm run start
    working_dir: /node/client
    depends_on:
      - app
    volumes:
      - ./packages/app/client:/node/client
    environment:
      - REACT_APP_PROXY_URL=http://app:5000
    ports:
      - 3000:3000
    restart: unless-stopped

  mongo:
    image: mongo:4.2.2-bionic
    restart: unless-stopped
    ports:
      - 27017:27017

volumes:
  discovery:
  parity1_data:
  contracts:
