version: "3.6"
services:
  app:
    depends_on:
      - mongo
      - parity1
    build: .
    volumes:
      - /app/node_modules
      - ./:/app
    working_dir: /app
    environment:
      - MONGO_URI=mongodb://mongo:27017/app
      - SECRET_OR_KEY=raging-dog-cat
      - TWITTER_CONSUMER_KEY=FsHO0rDJHSPSGp1NziEvvMQVH
      - TWITTER_CONSUMER_SECRET=7HZ1dBNgZZCp9hCHifgBAzRnm854aOAAkV5JviOiNp75O9nijE
      - TWITTER_ACCESS_TOKEN_KEY=54769191-yWo7yPEa0KFil2a43fshTw5KrvJkHVrgqCM1aBcLf
      - TWITTER_ACCESS_TOKEN_SECRET=sj7IqcBDRnmTjBZ0fp6pvNSeZCL8Wq8RmXTWO35LhQW1v
      - GITHUB_ACCESS_TOKEN=3099b3cc8f0ff3a8908a8c73330b00607aaa93d5
      - ETHEREUM_PROVIDER_URL=http://parity1:8545
      # - ETHEREUM_PROVIDER_USERNAME=undefined
      # - ETHEREUM_PROVIDER_PASSWORD=undefined
      - UN_ADMIN_PRIVATE_KEY=0xeaf6b1eeb57d9494e3036f231a7fb17c59aae1ab8de6b707076fb5b1956a1645
      - BADGE_1_ADDRESS=0x07EABe14480c77E88a57BACBda8E741De073eAeE
      - BADGE_2_ADDRESS=0x01BFCca990dfB2E0C475497C4Ce4893c44f94E34
      - BADGE_3_ADDRESS=0x867506629aa1711Eb8d3B49Ae2372382845994BE
      - BADGE_4_ADDRESS=0xd102659E8B360427B68c76d41D1c96E766Fa79AF
      - PORT=5000
    ports:
      - 5000:5000
  discovery:
    hostname: discovery
    image: redis
    networks:
    - main
    volumes:
      - discovery:/data
  parity1:
    hostname: un-bfpeace-parity1
    build:
      context: ./parity-stack
      dockerfile: Dockerfile-parity
      args:
        - PARITY_ID=1
        - NPM_TOKEN
        - S3_ACCESS_KEY_ID
        - S3_SECRET_ACCESS_KEY
        - S3_BUCKET_NAME
    environment:
      - PARITY_ID=1
    depends_on:
      - discovery
      - setup
    networks:
    - main
    ports:
      # - 8180:8180
      # - 8545:8545
      # - 8546:8546
      - 30303:30303
    image: appliedblockchain/un-bfpeace-parity1:latest
    volumes:
      - parity1_data:/parity/data
    depends_on:
      - discovery
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.node_id == 2
  ui:
    depends_on:
      - app
    build: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - REACT_APP_PROXY_URL=http://app:5000
    ports:
      - 3000:3000
  mongo:
    image: mongo
    restart: always

volumes:
  discovery:
  parity1_data:

networks:
  main:
