export const ADD_FILTER = 'projects/ADD_FILTER'
export const REMOVE_FILTER = 'projects/REMOVE_FILTER'
export const CLEAR_FILTERS = 'projects/CLEAR_FILTERS'
export const SAVE_PROJECTS = 'projects/SAVE_PROJECTS'
export const TOGGLE_LIKE = 'projects/TOGGLE_LIKE'
export const SET_PROJECT_VIEW = 'projects/SET_PROJECT_VIEW'
export const EDIT_UPDATE = 'projects/EDIT_UPDATE'
