export const SAVE_USER_INFO = 'profile/SAVE_USER_INFO'
export const SAVE_PROJECTS = 'profile/SAVE_PROJECTS'
export const LIKE_PROJECT = 'profile/LIKE_PROJECT'
export const SAVE_ACTIVITIES = 'profile/SAVE_ACTIVITIES'
export const SET_LOAD_MORE_FLAG = 'profile/SET_LOAD_MORE_FLAG'
