apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forum
  name: forum-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
        - args:
            - sh
            - -ac
            - echo "{\"url\":\"$URL\",\"port\":\"$PORT\",\"secret\":\"$SESSION_SECRET\",\"database\":\"mongo\",\"mongo\":{\"host\":\"$DATABASE_HOST\",\"port\":\"$DATABASE_PORT\",\"database\":\"$DATABASE_NAME\"}}" > config.json && node app --setup "{\"admin:username\":\"$ADMIN_USERNAME\",\"admin:password\":\"$ADMIN_PASSWORD\",\"admin:password:confirm\":\"$ADMIN_PASSWORD\",\"admin:email\":\"$ADMIN_EMAIL\"}" --defaultPlugins "[\"nodebb-plugin-session-sharing\", \"nodebb-plugin-mentions\"]" && ./nodebb start
          env:
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: forum-admin-email
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: forum-admin-password
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: forum-admin-username
            - name: DATABASE_NAME
              value: forum
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_host
            - name: DATABASE_PORT
              value: "27017"
            - name: PORT
              value: "4567"
            - name: SESSION_SECRET
              value: raging-dog-cat
            - name: URL
              value: localhost
          image: appliedblockchain/node-bb-atrium
          name: forum
          ports:
            - containerPort: 4567
      imagePullSecrets:
        - name: appliedblockchain-reg
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: forum-service
spec:
  selector:
    app: forum
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discovery
  name: discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - image: redis
          name: discovery
          ports:
            - containerPort: 6379
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: discovery
spec:
  selector:
    app: discovery
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - args:
            - ./bin/entrypoint.sh
          env:
            - name: ATRIUM_WALLET_SECRET
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: atrium-wallet-secret
            - name: ETHEREUM_NODE
              value: blockchain-service
            - name: ETHEREUM_PROVIDER_URL
              value: http://blockchain-service:8545
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/app
            - name: PORT
              value: "5000"
            - name: SECRET_OR_KEY
              value: raging-dog-cat
            - name: TRUFFLE_NETWORK
              value: kube_development
            - name: AWS_SES_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: aws-ses-access-key
            - name: AWS_SES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: aws-ses-secret-key
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: aws-access-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: aws-secret-key
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: aws-bucket-name
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: client_url
            - name: ATTACHMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: attachment_url
          image: appliedblockchain/atrium-app
          name: unin-app
          ports:
            - containerPort: 5000
          workingDir: /node/app
      imagePullSecrets:
        - name: appliedblockchain-reg
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: remix
  name: remix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remix
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: remix
    spec:
      containers:
        - image: appliedblockchain/remix-atrium
          name: remix
          ports:
            - containerPort: 80
          resources: {}
      imagePullSecrets:
        - name: appliedblockchain-reg
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: remix
  name: remix
spec:
  ports:
    - name: "8080"
      port: 80
      targetPort: 80
  selector:
    app: remix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - env:
            - name: SECRET_OR_KEY
              value: raging-dog-cat
          image: appliedblockchain/atrium_reverse-proxy
          name: reverse-proxy
          ports:
            - containerPort: 5000
          resources: {}
      imagePullSecrets:
        - name: appliedblockchain-reg
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverse-proxy
  name: reverse-proxy
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: reverse-proxy
