apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forum
  name: forum-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
        - args:
            - sh
            - -ac
            - echo "{\"url\":\"$URL\",\"port\":\"$PORT\",\"secret\":\"$SESSION_SECRET\",\"database\":\"mongo\",\"mongo\":{\"host\":\"$DATABASE_HOST\",\"port\":\"$DATABASE_PORT\",\"database\":\"$DATABASE_NAME\"}}" > config.json && node app --setup "{\"admin:username\":\"$ADMIN_USERNAME\",\"admin:password\":\"$ADMIN_PASSWORD\",\"admin:password:confirm\":\"$ADMIN_PASSWORD\",\"admin:email\":\"$ADMIN_EMAIL\"}" --defaultPlugins "[\"nodebb-plugin-session-sharing\", \"nodebb-plugin-mentions\"]" && ./nodebb start
          env:
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: forum-admin-email
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: forum-admin-password
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: forum-admin-username
            - name: DATABASE_NAME
              value: forum
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_host
            - name: DATABASE_PORT
              value: "27017"
            - name: PORT
              value: "4567"
            - name: SESSION_SECRET
              value: raging-dog-cat
            - name: URL
              value: localhost
          image: appliedblockchain/node-bb-atrium
          name: forum
          ports:
            - containerPort: 4567
      imagePullSecrets:
        - name: appliedblockchain-reg
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: forum-service
spec:
  selector:
    app: forum
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: parity
  name: parity-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: parity
  template:
    metadata:
      labels:
        app: parity
    spec:
      containers:
        - env:
            - name: PARITY_ID
              value: "1"
          image: appliedblockchain/parity-solo
          name: parity
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 30303
      imagePullSecrets:
        - name: appliedblockchain-reg
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: parity-service
spec:
  selector:
    app: parity
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
      name: http-rpc
    - protocol: TCP
      port: 8546
      targetPort: 8546
      name: ws-rpc
    - protocol: TCP
      port: 30303
      targetPort: 30303
      name: gossip
---
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: init
    spec:
      containers:
        - env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_host
            - name: ATRIUM_WALLET_SECRET
              valueFrom:
                secretKeyRef:
                  name: atrium-secret
                  key: atrium-wallet-secret
            - name: ETHEREUM_PROVIDER_HOST
              valueFrom:
                configMapKeyRef:
                  name: parity-configmap
                  key: parity_host
            - name: ETHEREUM_PROVIDER_URL
              value: http://$(ETHEREUM_PROVIDER_HOST):8545
            - name: MONGO_URI
              value: "mongodb://$(DATABASE_HOST):27017/app"
          image: init
          name: init
          resources: {}
          volumeMounts:
            - mountPath: /contracts
              name: contracts
      restartPolicy: Always
      volumes:
        - name: contracts
          persistentVolumeClaim:
            claimName: contracts
