apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ganache
  name: ganache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - args:
            - --gasLimit
            - "9900000000"
            - --gasPrice
            - "0"
            - --db=/ganache_data
          image: trufflesuite/ganache-cli:latest
          name: ganache
          ports:
            - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
spec:
  selector:
    app: ganache
  ports:
    - name: "http-rpc"
      port: 8545
      targetPort: 8545
