apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-dev.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: init
  name: init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: init
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-dev.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: init
    spec:
      containers:
        - env:
            - name: ATRIUM_WALLET_SECRET
              value: dev
            - name: ETHEREUM_PROVIDER_URL
              value: http://parity1:8545
            - name: MONGO_URI
              value: mongodb://mongo:27017/app
          image: init
          name: init
          resources: {}
          volumeMounts:
            - mountPath: /contracts
              name: contracts
      restartPolicy: Always
      volumes:
        - name: contracts
          persistentVolumeClaim:
            claimName: contracts
status: {}
