apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-dev.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: parity1
  name: parity1
spec:
  ports:
    - name: "8545"
      port: 8545
      targetPort: 8545
    - name: "8546"
      port: 8546
      targetPort: 8546
    - name: "30303"
      port: 30303
      targetPort: 30303
  selector:
    io.kompose.service: parity1
status:
  loadBalancer: {}
