apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-dev.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-dev.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - args:
            - npm
            - run
            - start
          env:
            - name: REACT_APP_PROXY_URL
              value: http://app:5000
          image: node:erbium-alpine3.11
          name: unin-client
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /node/client
              name: ui-claim0
          workingDir: /node/client
      restartPolicy: Always
      volumes:
        - name: ui-claim0
          persistentVolumeClaim:
            claimName: ui-claim0
status: {}
