export { default as DiscussionPage } from './DiscussionPage'
export { default as DiscussionDetails } from './DiscussionDetails'
export { default as ProfilePage } from './ProfilePage'
export { default as ProjectDetails } from './ProjectDetails/ProjectDetails'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as ForgotPassword } from './ForgotPassword'
export { default as ResetPassword } from './ResetPassword'
