module.exports = {
  MONGO_URI: process.env.MONGO_URI,
  SECRET_OR_KEY: process.env.SECRET_OR_KEY,
  GITHUB_ACCESS_TOKEN: process.env.GITHUB_ACCESS_TOKEN,
  ETHEREUM_PROVIDER_URL: process.env.ETHEREUM_PROVIDER_URL,
  ETHEREUM_PROVIDER_USERNAME: process.env.ETHEREUM_PROVIDER_USERNAME,
  ETHEREUM_PROVIDER_PASSWORD: process.env.ETHEREUM_PROVIDER_PASSWORD,
  UN_ADMIN_PRIVATE_KEY: process.env.UN_ADMIN_PRIVATE_KEY,
  BADGE_1_ADDRESS: process.env.BADGE_1_ADDRESS,
  BADGE_2_ADDRESS: process.env.BADGE_2_ADDRESS,
  BADGE_3_ADDRESS: process.env.BADGE_3_ADDRESS,
  BADGE_4_ADDRESS: process.env.BADGE_4_ADDRESS,
  NODE_ENV: process.env.NODE_ENV ? process.env.NODE_ENV : 'development'
}
