module.exports = {
  BLOCKCHAIN: 'BLOCKCHAIN',
  CRYPTOCURRENCY: 'CRYPTOCURRENCY',
  WALLETS: 'WALLETS',
  ETHEREUM: 'ETHEREUM',
  BITCOIN: 'BITCOIN',
  USE_CASES: 'USE_CASES',
  SUPPLEMENTARY_RESOURCES: 'SUPPLEMENTARY_RESOURCES',
  OTHER: 'OTHER'
}